### ISSUE TITLE
1.2.0 - passing wrong arguments

### ISSUE THREAD

**Issue by albertosantini** [nkcmr/flic#14]
In `Node` constructor there is an attempt to handle the old interface with `id` and `callback` with the new one, the config object.

The point is `createNode` passes only the first parameter, in this case `id`, vanishing the use of `arguments` in `Node` constructor.

I think the `arguments` trick should be done there and not in `Node` constructor: it is too late.

Indeed if I try to use the example contained in the README, it doesn't work.
Using the new interface and passing the config object with `id` and `connect_callback` it works nicely.

Luckly, my old code used `require("flic").node` and I didn't notice any problem.
After upgrading the code with `createNode`, the app stopped to work correctly.

**Comment by nkcmr** [comment]
@albertosantini woah! good catch. i have fixed the problem, you can now use `createNode` like you would `new node`. although i wouldn't expect those parameters in constructor to remain the same for `v2.0.0`.

**Comment by albertosantini** [comment]
Thanks for the quick fix! :)
