### ISSUE TITLE
Add callback to createBridge so that failures can be dealt with

### ISSUE THREAD

**Issue by allain** [nkcmr/flic#15]
This can happen it two processes create a bridge at the same time. The second one will fail silently, and really shouldn't.

In the case where I have a bunch of processes and 1 master, the first to create the bridge could declare itself the master. For that case, I need to be able to tell when it fails.

**Comment by nkcmr** [comment]
thanks for the issue submission @allain! i have added a callback to bridge construction in #16. this is now available in `v1.2.3` on npm.
