### ISSUE TITLE
Host configuration

### ISSUE THREAD

**Issue by albertosantini** [nkcmr/flic#2]
Maybe I have been missing something, but I cannot see any host configuration.

It seems I can scale vertically, but if my nodes are distributed to remote machines, I cannot see how to set the host.

It would be interesting to change Node API, for instance, as `new Node( [name], [host], [port], [callback] )`, where parameter `host` is the Bridge host.

Does it make sense?

**Comment by nkcmr** [comment]
@albertosantini there is *not* currently a way to configure `host` on a node. i am planning a `2.0` release and this will definitely be a part of it.

**Comment by albertosantini** [comment]
Fair enough. Thanks.
